on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/badges-action-markdown.yml'

jobs:
  update-profile-badges:
    runs-on: ubuntu-latest
    name: Update profile badges
    steps:
      - name: Update Badges
        uses: kamuridesu/markdown-badges@v0.0.2
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BADGES: "Python Golang Java 'Sublime Text' 'Visual Studio Code'"
